config/routes.rb
Rails.application.routes.draw do

  root 'statics#home'

  resources :photographs
  post '/profile_picture', to: 'photographs#upload_profile_pic'
  post '/change_profile_pic', to: 'photographs#change_profile_pic'

  resources :galleries
  get '/mygallery', to: 'galleries#mygallery'
  devise_for :users


  resources :users, only: [:index]
  resources :profiles do
    member do
      get 'like'
      get 'unlike'
    end
  end

  get '/myprofile', to: 'profiles#myprofile'
  get '/i_like', to: 'profiles#i_like'
  get '/likes_me', to: 'profiles#likes_me'
  get '/mutual_likes', to: 'profiles#mutual_likes'

  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]



  mount ActionCable.server => '/cable'

end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user

  #this model can be voted/liked
  acts_as_votable

  paginates_per 20

  def profile_picture
    Photograph.where(gallery_id: self.user.gallery.id).where(profile_picture: true)
  end




end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :set_my_profile, only: [:myprofile, :likes_me, :i_like, :mutual_likes]
  before_action :set_profile_picture, only: [:myprofile, :edit, :update, :destroy]
  before_action :find_conversation!, only: [:show]
  # before actions for likes
  before_action :find_likes_me, only: [:myprofile, :likes_me, :mutual_likes]
  before_action :find_who_i_like, only: [:myprofile, :i_like]
  before_action :find_mutual_likes, only: [:myprofile, :mutual_likes]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all.page params[:page]
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    #@profile_picture = Photograph.find_profile_picture(@profile.user.gallery.id).first
    @profile_picture = @profile.profile_picture.first
    @conversation = Conversation.between(current_user.id, @profile.user.id).first

    @personal_message = PersonalMessage.new
  end


  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit

  end

  # POST /profiles
  # POST /profiles.json
  def create

    @profile = Profile.new(profile_params)
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update

    respond_to do |format|
      if @profile.update(profile_params)
        puts profile_params
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
end

  def update_profile_image
    @profile = Profile.where(user_id: current_user.id).first

    @profile.temp_url = params["profile"]["image"].tempfile.path

    respond_to do |format|
      if @profile.update(profile_params)
        puts profile_params
        format.html { redirect_to @profile, notice: 'Profile Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def myprofile

    @conversations = Conversation.participating(current_user).order('updated_at ASC')


  end

  def i_like
    @user_who_likes = Kaminari.paginate_array(@user_who_likes).page(params[:page]).per(10)
  end

  def likes_me
    @user_likes = Kaminari.paginate_array(@user_likes).page(params[:page]).per(10)
  end

  def mutual_likes
    @user_mutual_likes = Kaminari.paginate_array(@user_mutual_likes).page(params[:page]).per(10)
  end

  def like
    puts "........................................................"
    puts "i like you"
    if @profile.liked_by current_user
      respond_to do |format|
        format.html {redirect_back(fallback_location: @profile)}
        format.js
      end
    end
  end

  def unlike
    puts "........................................................"
    puts "i dont like you anymore"
    if @profile.unliked_by current_user
      respond_to do |format|
        format.html {redirect_back(fallback_location: @profile)}
        format.js
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def set_my_profile
      @profile = Profile.where(user_id: current_user.id).first
    end

    # Get the correct profile Picture
    def set_profile_picture
        @profile_picture = Photograph.find_profile_picture(current_user.gallery.id).first

    end

    def find_conversation!

        @receiver = Profile.where(id: params[:id]).first.user
        @conversation = Conversation.between(current_user.id, @profile.user.id).first

    end

    def find_likes_me
      # returns users array
      @user_likes = @profile.votes_for.voters
      puts "WHO LIKES ME"
      puts @user_likes
    end

    def find_who_i_like
      # returns profiles array
      @user_who_likes = current_user.find_up_voted_items
      puts "WHO I LIKE"
      puts @user_who_likes
    end

    def find_mutual_likes
      @user_mutual_likes = Array.new
      @user_likes.each do |user|
        if current_user.voted_for? user.profile
          puts "he likes too"
          @user_mutual_likes.push(user.profile)
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :firstname, :lastname, :nickname, :age, :profession, :about, :catchphrase, :introduction, :gender,:height,:weight, :hair_color, :eye_color, :relationship_status, :religion, :has_children, :wants_children, :smoking, :drinking, :wants_to_meet, :ethnic, :education, :looking_gender, looking_for: [])
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  # Helper method for the checkboxes
  def checked(area)
    unless @profile.looking_for.nil?
      @profile.looking_for.include? area
    end
  end


  # Helper methods for the selects

  def options_eye_color
    [
      ['Blue', 'Blue'],
      ['Brown', 'Brown'],
      ['Green', 'Green'],
      ['Grey', 'Grey'],
      ['Darkbrown', 'Darkbrown']
    ]
  end

  def options_hair_color
    [
      ['Black', 'Black'],
      ['Brown', 'Brown'],
      ['Blonde', 'Blonde'],
      ['Dark blonde', 'Dark blonde'],
      ['Dyed', 'Dyed'],
      ['Grey', 'Grey'],
      ['Red', 'Red']
    ]
  end

  def options_has_children
    [
      ['No', 'No'],
      ['Yes (lives with)', 'Yes (lives with)'],
      ["Yes (Don't lives with)", "Yes (Don't lives with)"]
    ]
  end

  def options_wants_children
    [
      ['Yes', 'Yes'],
      ['No', 'No'],
      ['Maybe', 'Maybe']
    ]
  end

  def options_smoking
    [
      ['Yes', 'Yes'],
      ['No', 'No'],
      ['Social smoker', 'Social Smoker']
    ]
  end

  def options_drinking
    [
      ['Yes', 'Yes'],
      ['No', 'No'],
      ['Social drinker', 'Social dinker']
    ]
  end

  def options_religion
    [
      ['Agnostic', 'Agnostic'],
      ['Atheist', 'Atheist'],
      ["Baha'ist", "Baha'ist"],
      ['Buddhist', 'Buddhist'],
      ['Caodaism', 'Caodaism'],
      ['Christian - Protestant', 'Christian - Protestant'],
      ['Christian - Catholic', 'Christian - Catholic'],
      ['Christian - Mormon', 'Christian - Mormon'],
      ['Christian - Orthodox', 'Christian - Orthodox'],
      ['Christian - Other', 'Christian - Other'],
      ['Confucianism', 'Confucianism'],
      ['Hindu', 'Hindu'],
      ['Iscon', 'Iscon'],
      ['Islam Shiite', 'Islam Shiite'],
      ['Islam Sunni', 'Islam Sunni'],
      ['Jainism', 'Jainism'],
      ['Jewish', 'Jewish'],
      ['No Religion', 'No Religion'],
      ['Other', 'Other'],
      ['Pentecostal', 'Pentecostal'],
      ['Shintoism', 'Shintoism'],
      ['Sikhism', 'Sikhism'],
      ['Taoism', 'Taoism'],
    ]
  end

  def options_relationship_status
    [
      ['Single', 'Single'],
      ['Taken', 'Taken'],
      ['Married', 'Married'],
      ['Divorced', 'Divorced'],
      ['Complicated', 'Complicated'],
      ['Separated', 'Separated'],
      ['Widow / Widower', 'Widow / Widower']
    ]
  end

  def options_education
    [
      ['No education', 'No education'],
      ['Elementary School', 'Elementary School'],
      ['Highschool', 'Highschool'],
      ['College', 'College'],
      ['University - Bachelors Degree', 'University - Bachelors Degree'],
      ['University - Masters Degree', 'University - Masters Degree'],
      ['Phd / Doctorate', 'Phd Doctorate'],
      ['Other', 'Other']
    ]
  end

  def options_ethnicity
    [
      ['African (Black)', 'African (Black)'],
      ['African American', 'African American'],
      ['Arab (Middle Eastern)', 'Arab (Middle Eastern)'],
      ['Asian', 'Asian'],
      ['Caucasian (White)', 'Caucasian (White)'],
      ['East Indian', 'East Indian'],
      ['Hispanic', 'Hispanic'],
      ['Latino', 'Latino'],
      ['Mixed', 'Mixed'],
      ['Other', 'Other']
    ]
  end

  def options_gender
    [
      ['Male', 'Male'],
      ['Female', 'Female']
    ]
  end

  def options_looking_gender
    [
      ['Male', 'Male'],
      ['Female', 'Female'],
      ['Both', 'Both']
    ]
  end

end

app/views/profiles/_form.html.erb
<div class="row">
  <div class="col s12">


    <div class="card">
    <div class="card-content">
      <div class="container">
        <%= form_with(model: profile, local: true) do |form| %>

          <% if @profile.errors.any? %>
            <% puts "has Errors" %>
            <% @profile.errors.each do |attribute, message| %>
              <p><%= attribute %></p>
              <p><%= message %></p>
            <% end %>

          <% end %>

        <div class='row'>
          <div class='col s12'>
          </div>
        </div>

          <div class="col s3">
            <div class="card">
              <div class="card-image">
                <div class="profile-image-wrapper">

                    <%= has_profile_picture(@profile_picture) %>

                </div>

              </div>

                <div class="card-action">
                  <a class="waves-effect waves-light btn" href="#ProfilePicture">Change Picture</a>
                </div>

            </div>
          </div>


        <!-- Basic informtions -->
        <div class="col s9">
          <center><h5>Your name</h5></center>
        <div class="col s6">
          <div class='row'>
            <div class="input-field col s12">
              <%= form.text_field :firstname, id: :profile_firstname %>
              <label for="firstname" class="<%= @profile.firstname.present? ? "active" : ""%>">Firstname</label>
            </div>
          </div>
        </div>
        <div class="col s6">
          <div class='row'>
            <div class="input-field col s12">
              <%= form.text_field :lastname, id: :profile_lastname %>
              <label for="lastname" class="<%= @profile.lastname.present? ? "active" : ""%>">Lastname</label>
            </div>
          </div>
        </div>
        <div class="col s12">
          <div class='row'>
            <div class="input-field col s12">
              <%= form.text_field :nickname, id: :profile_nickname %>
              <label for="nickname" class="<%= @profile.nickname.present? ? "active" : ""%>">Nickname</label>
            </div>
          </div>
        </div>

        <!-- LEFT PART -->
        <center><h5>Personal Information</h5></center>

        <div class="col s6">
          <div class='row'>
            <div class="input-field col s12">
              <%= form.select :gender, options_gender,{} %>
              <label for="nickname">Gender</label>
            </div>
          </div>
          <div class='row'>
            <div class="input-field col s12">
              <%= form.number_field :age, id: :profile_age %>
              <label for="age" class="<%= @profile.age.present? ? "active" : ""%>">Age</label>
            </div>
          </div>
          <div class='row'>
            <div class="input-field col s12">
              <%= form.text_field :height, id: :height %>
              <label for="height" class="<%= @profile.height.present? ? "active" : ""%>">Height</label>
            </div>
          </div>

          <div class='row'>
            <div class="input-field col s12">
              <%= form.text_field :weight, id: :weight %>
              <label for="weight" class="<%= @profile.weight.present? ? "active" : ""%>">Weight</label>
            </div>
          </div>
          <div class='row'>
            <div class="input-field col s12">
              <%= form.select :religion, options_religion,{} %>
              <label>Religion</label>
            </div>
          </div>
          <div class='row'>
            <div class="input-field col s12">
              <%= form.select :education, options_education,{} %>
              <label>Education</label>
            </div>
          </div>
          <div class='row'>
            <div class="input-field col s12">
              <%= form.text_field :profession%>
              <label>Occupation</label>
            </div>
          </div>
          <div class='row'>
            <div class="input-field col s12">
              <%= form.select :ethnic, options_ethnicity,{} %>
              <label >Ethnicity</label>
            </div>
          </div>
        </div>
        <!-- RIGHT PART -->
        <div class="col s6">
          <div class='row'>
            <div class="input-field col s12">
              <%= form.select :hair_color, options_hair_color,{} %>
              <label for="hair_color" >Hair color</label>
            </div>
          </div>
          <div class='row'>
            <div class="input-field col s12">
              <%= form.select :eye_color, options_eye_color,{} %>

              <label class="<%= @profile.eye_color.present? ? "active" : ""%>">Eye color</label>
            </div>
          </div>
          <div class='row'>
            <div class="input-field col s12">
              <%= form.select :has_children, options_has_children,{} %>
              <label>Has children</label>
            </div>
          </div>
          <div class='row'>
            <div class="input-field col s12">
              <%= form.select :wants_children, options_wants_children,{} %>
              <label >Wants children</label>
            </div>
          </div>
          <div class='row'>
            <div class="input-field col s12">
              <%= form.select :smoking, options_smoking,{} %>
              <label>Smoking</label>
            </div>
          </div>
          <div class='row'>
            <div class="input-field col s12">
              <%= form.select :drinking, options_drinking, {} %>
              <label for="drinking">Drinking</label>
            </div>
          </div>
          <div class='row'>
            <div class="input-field col s12">
              <%= form.select :relationship_status, options_relationship_status,{} %>
              <label>Relationship status</label>
            </div>
          </div>
        </div>
      </div>
        <div class='row'>
          <div class="input-field col s12">
            <%= form.text_area :about, id: :profile_about, class: "materialize-textarea" %>
            <label for="about" class="<%= @profile.about.present? ? "active" : ""%>">Tell Something about yourself</label>
          </div>
        </div>
        <div class='row'>
          <div class="input-field col s12">
            <div class="field">
              <label for="catchphrase" class="<%= @profile.catchphrase.present? ? "active" : ""%>">Your Catchphrase</label>
              <%= form.text_area :catchphrase, id: :profile_catchphrase, class: "materialize-textarea"%>
            </div>
          </div>
        </div>
        <center><h4>Looking for </h4></center>
        <div class="row">
          <div class="input-field col s12">
            <%= form.select :looking_gender, options_looking_gender, {} %>
            <label >What Gender your looking for</label>
          </div>
        </div>
        <div>
        <div class="row">
          <div class="input-field col s12">
            <p>
              <%= check_box_tag "profile[looking_for][]", 'Relationship', checked('Relationship'), id:"relationship" %>
              <label for="relationship">Relationship</label>
            </p>
            <p>
              <%= check_box_tag "profile[looking_for][]", 'Dating', checked('Dating'), id:"dating" %>
              <label for="dating">Dating</label>
            </p>
            <p>

              <%= check_box_tag "profile[looking_for][]", 'Friends', checked('Friends'), id:"friends" %>
              <label for="friends">Friends</label>
            </p>
            <p>
              <%= check_box_tag "profile[looking_for][]", 'Networking', checked('Networking'), id:"networking" %>
              <label for="networking">Networking</label>
            </p>
        </div>
        </div>
        <center>
          <div class='row'>
            <div class="actions">
              <%= form.submit "Submit", class:"btn waves-effect waves-light" %>
            </div>
          </div>
        </center>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

<!-- Modal Structure -->
<div id="ProfilePicture" class="modal modal-fixed-footer">
  <%= form_for :photograph, url: {controller: 'photographs' ,action: "upload_profile_pic"} do |f| %>
  <div class="modal-content">
    <a class="modal-close close-modal-button"><i class="fa fa-close fa-4x"></i></a>
    <h4>Change your Profile Picture</h4>
      <div class="col s4">
        <div class="card">
          <div class="card-image">
          <div id="imgPreview">
            <div class="profile-image-wrapper">
                <%= has_profile_picture(@profile_picture) %>
            </div>
          </div>
        </div>
      </div>
      </div>
      <div class="col s8">
        <h5>Rules:</h5>
        <ul>
          <li>1. It has to be a picture of yourself.</li>
          <li>2. Only pictures with your Face is allowed.</li>
          <li>3. No pictures with more than one face.</li>
          <li>3. No nudity, violence or any other inappropiate content is allowed.</li>
        </ul>

            <div class="gallery row">
              <h5>Choose existing Picture or upload a new one</h5>
              <div class="masonry">
              <% current_user.gallery.photographs.each do |photo| %>
                <div class="masonry-item">
                     <i class="masonry-item-icon small material-icons" style="color:#ef5350">add_circle</i>
                     <%= image_tag(photo.image_url.to_s , class:"fit-image responsive-img", photoId: photo.id) %>
                </div>
              <% end %>
            </div>
            </div>



      </div>
  </div>
  <div class="modal-footer">
    <div class="actions">

      <%= f.submit "Upload new File", id:"uploadPicture", class:"btn waves-effect waves-light", style:"display:none;" %>

      <a id="changeProfile" class="waves-effect waves-light btn" style="margin-left: 10px; display:none;"><i class="small material-icons left">save</i> Change with existing</a>

      <label for="file-input">
        <a class="waves-effect waves-light btn" style="margin-right: 10px;" ><i class="small material-icons left">add_a_photo</i> Choose New File</a>
      </label>
      <%= f.file_field :image, id:"file-input", hidden:true , :required => 'required'  %>

    </div>
  </div>
  <% end %>
</div>

app/views/profiles/_profile.html.erb
<div class="col s3">

  <div class="card">
    <a href="<%= profile_path(profile.id)%>">
      <div class="card-image">
        <div class="profile-image-wrapper">
          <%= has_profile_picture(profile.profile_picture.first) %>
        </div>
      </div>
    </a>
    <div class="card-content">
        <p class="activator"><%= profile.age %>, <%= profile.nickname %><i class="material-icons right">more_vert</i></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text">About<i class="material-icons right">close</i></span>
      <p><%= profile.about %></p>
    </div>
  </div>

</div>

app/views/profiles/edit.html.erb
<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/i_like.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <ul class="collection">
        <% @user_who_likes.each do |voter| %>
          <li class="collection-item avatar">
            <%= get_thumbnail(voter.user)%>
            <span class="title"><%= voter.nickname %></span>
            <p><%= voter.age %></p>
          </li>

        <% end %>
      </ul>
    </div>

  </div>
  <%= paginate @user_who_likes %>
</div>

app/views/profiles/index.html.erb
<div class="container">
  <center><h4>Users</h4></center>

  <div class="row">

    <div class="col s12">
      <%= render @profiles %>
    </div>

  </div>
  <%= paginate @profiles %>
</div>

app/views/profiles/likes_me.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <ul class="collection">
        <% @user_likes.each do |voter| %>
          <li class="collection-item avatar">
            <%= get_thumbnail(voter)%>
            <span class="title"><%= voter.profile.nickname %></span>
            <p><%= voter.profile.age %></p>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/profiles/myprofile.html.erb
<div class="row">
  <div class="col s12">

    <div class="container">

      <div class='row'>

        <div class='col s12'>
        </div>
      </div>
      <div class="col s3">
        <h4><%= @profile.nickname %></h4>
        <div class="card">
          <div class="card-image">
            <div class="profile-image-wrapper">
              <%= has_profile_picture(@profile_picture) %>
            </div>
            <div class="card-content">
              <center><h5>Personal Information</h5></center>
              <table class="no-spacing"cellspacing="0">
                <tr>
                  <td>Firsname:</td>
                  <td><%=@profile.firstname %></td>
                </tr>
                <tr>
                  <td>Lastname:</td>
                  <td><%= @profile.lastname %></td>
                </tr>
                <tr>
                  <td>Age:</td>
                  <td><%= @profile.age %></td>
                </tr>
                <tr>
                  <td>Gender:</td>
                  <td><%= @profile.gender %></td>
                </tr>
                <tr>
                  <td>Height:</td>
                  <td><%= @profile.height %></td>
                </tr>
                <tr>
                  <td>Weight:</td>
                  <td><%= @profile.weight %></td>
                </tr>
                <tr>
                  <td>Hair color:</td>
                  <td><%= @profile.hair_color %></td>
                </tr>
                <tr>
                  <td>Eye color:</td>
                  <td><%= @profile.eye_color %></td>
                </tr>
                <tr>
                  <td>Ethnicity:</td>
                  <td><%= @profile.ethnic %></td>
                </tr>

              </table>
              <center><h5>Other Information</h5></center>
              <table class="no-spacing">
                <tr>
                  <td>Education:</td>
                  <td><%=@profile.education %></td>
                </tr>
                <tr>
                  <td>Occupation:</td>
                  <td><%=@profile.profession %></td>
                </tr>
                <tr>
                  <td>Religion:</td>
                  <td><%=@profile.religion %></td>
                </tr>
                <tr>
                  <td>Smoking:</td>
                  <td><%= @profile.smoking %></td>
                </tr>
                <tr>
                  <td>Drinking:</td>
                  <td><%= @profile.drinking %></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>

      <div class="col s9">
        <div class="row">
          <div class="col s12">
            <h4>Recent Conversations</h4>
            <%= render @conversations.limit(2) %>
            <center><a href="<%=conversations_path %>" class="btn waves-effect waves-light">More</a></center>
          </div>
        </div>
        <!-- Make a list for all likes -->
        <div class="row">
          <div class="col s12">

            <ul class="tabs">
              <li class="tab col s4"><a href="#likesMe">Likes Me</a></li>
              <li class="tab col s4"><a href="#mutualLike">Mutual like</a></li>
              <li class="tab col s4"><a href="#whoILike">Who i like</a></li>
            </ul>
            <!-- Here is a list of all people that likes the profile (max 5) -->
            <div id="likesMe">
              <ul class="collection">
                <% @user_likes[0..4].each do |voter| %>
                  <li class="collection-item avatar">
                    <%= get_thumbnail(voter)%>
                    <span class="title"><%= voter.profile.nickname %></span>
                    <p><%= voter.profile.age %></p>
                  </li>

                <% end %>
              </ul>
              <center><a href="<%= likes_me_path %>" class="btn waves-effect waves-light">More</a></center>
            </div>
            <!-- Here is a list of the people who lick eachother -->
            <div id="mutualLike">
              <ul class="collection">
                <% @user_mutual_likes[0..4].each do |voter| %>
                  <li class="collection-item avatar">
                    <%= get_thumbnail(voter.user)%>
                    <span class="title"><%= voter.nickname %></span>
                    <p><%= voter.age %></p>
                  </li>

                <% end %>
              </ul>
              <center><a href="<%= mutual_likes_path %>" class="btn waves-effect waves-light">More</a></center>
            </div>
            <div id="whoILike">
              <ul class="collection">
                <% @user_who_likes[0..4].each do |voter| %>
                  <li class="collection-item avatar">
                    <%= get_thumbnail(voter.user)%>
                    <span class="title"><%= voter.nickname %></span>
                    <p><%= voter.age %></p>
                  </li>

                <% end %>
              </ul>
              <center><a href="<%= i_like_path %>" class="btn waves-effect waves-light">More</a></center>
            </div>

          </div>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col s12 m12 l12">

    <div class="container">

      <div class='row'>

        <div class='col s12'>
        </div>
      </div>
      <div class="col s12 m3 l3">

        <div class="card">
          <div class="card-image">
            <div class="profile-image-wrapper">
              <%= has_profile_picture(@profile_picture)%>
            </div>
            <div class="card-content">

              <!-- like / unlike buttons -->
              <% if current_user.liked? @profile %>
                <center><a href="<%= unlike_profile_path(@profile.id)%>"id="likeButton" class="btn waves-effect waves-light"><i class="large material-icons left" style="color:#ef5350">favorite</i>Unlike</a></center>
              <% else %>
                <center><a href="<%= like_profile_path(@profile.id)%>"id="likeButton" class="btn waves-effect waves-light"><i class="large material-icons left" style="color:#ef5350">favorite</i>Like</a></center>
              <% end %>

              <center><h5>Personal Information</h5></center>

              <table class="no-spacing"cellspacing="0">

                <tr>
                  <td>Nickname:</td>
                  <td><%=@profile.nickname %></td>
                </tr>
                <tr>
                  <td>Firsname:</td>
                  <td><%=@profile.firstname %></td>
                </tr>

                <tr>
                  <td>Lastname:</td>
                  <td><%= @profile.lastname %></td>
                </tr>
                <tr>
                  <td>Age:</td>
                  <td><%= @profile.age %></td>
                </tr>
                <tr>
                  <td>Gender:</td>
                  <td><%= @profile.gender %></td>
                </tr>
                <tr>
                  <td>Height:</td>
                  <td><%= @profile.height %></td>
                </tr>
                <tr>
                  <td>Weight:</td>
                  <td><%= @profile.weight %></td>
                </tr>
                <tr>
                  <td>Hair color:</td>
                  <td><%= @profile.hair_color %></td>
                </tr>
                <tr>
                  <td>Eye color:</td>
                  <td><%= @profile.eye_color %></td>
                </tr>
                <tr>
                  <td>Ethnicity:</td>
                  <td><%= @profile.ethnic %></td>
                </tr>

              </table>
              <center><h5>Other Information</h5></center>
              <table class="no-spacing">
                <tr>
                  <td>Education:</td>
                  <td><%=@profile.education %></td>
                </tr>
                <tr>
                  <td>Occupation:</td>
                  <td><%=@profile.profession %></td>
                </tr>
                <tr>
                  <td>Religion:</td>
                  <td><%=@profile.religion %></td>
                </tr>
                <tr>
                  <td>Smoking:</td>
                  <td><%= @profile.smoking %></td>
                </tr>
                <tr>
                  <td>Drinking:</td>
                  <td><%= @profile.drinking %></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>

        <div class="col s12 m9 l9">
          <% if @conversation.nil? %>
            <%= render :template => "personal_messages/new" %>
          <% else %>
            <%= render :template => "conversations/show"%>
          <% end %>
        </div>



        <div class="gallery col s12 m9 l9">

          <div class="masonry">
          <% @profile.user.gallery.photographs.each do |photo| %>
            <div class="masonry-item">
                 <i class="masonry-item-icon small material-icons" style="color:#ef5350">add_circle</i>
                 <%= image_tag(photo.image_url.to_s , class:"fit-image responsive-img", photoId: photo.id) %>
            </div>
          <% end %>
        </div>
        </div>


    </div>
  </div>

</div>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>