config/routes.rb
Rails.application.routes.draw do

  root 'statics#home'

  resources :photographs
  post '/profile_picture', to: 'photographs#upload_profile_pic'
  post '/change_profile_pic', to: 'photographs#change_profile_pic'

  resources :galleries
  get '/mygallery', to: 'galleries#mygallery'
  devise_for :users


  resources :users, only: [:index]
  resources :profiles do
    member do
      get 'like'
      get 'unlike'
    end
  end

  get '/myprofile', to: 'profiles#myprofile'
  get '/i_like', to: 'profiles#i_like'
  get '/likes_me', to: 'profiles#likes_me'
  get '/mutual_likes', to: 'profiles#mutual_likes'

  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]



  mount ActionCable.server => '/cable'

end

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">Text that will be places here in the footer</p>
      </div>
      <div class="col l4 offset-12 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      2017 Copyright Yourdate
    </div>
  </div>
</footer>

app/views/shared/_menu.html.erb
<% flash.each do |key,value| %>
  <div>
    <%= value %>
  </div>
<% end %>

<% if user_signed_in? %>
  <div id="current-user"></div
  <p>Signed in as <%= current_user.name %> | <%= link_to 'log out', destroy_user_session_path, method: :delete %></p>
<% end %>
<ul>
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'Users', users_path %></li>
</ul>

app/views/shared/_navigation.html.erb
<ul id="dropdown1" class="dropdown-content">
  <% if user_signed_in? then %>
    <li><a href="<%=profile_path(current_user.profile) %>">Profile</a></li>
    <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %> </li>
  <% end %>
</ul>
<nav>
  <div class="nav-wrapper">
    <a href="#" class="brand-logo"> Datesite</a>
    <ul class="right">
      <% if user_signed_in? then %>
      <li><a href="<%=root_path %>"><i class="material-icons left">home</i> Home</a></li>
      <li><a href="<%=profiles_path %>"><i class="material-icons left">search</i> Search</a></li>
      <li><a href="<%=myprofile_path %>"><i class="material-icons left">account_circle</i> My Profile</a></li>
      <li><a href="<%=mygallery_path %>"><i class="material-icons left">photo</i> Mygallery</a><li>
      <li><a href="<%=conversations_path %>"><i class="material-icons left">message</i> Messages</a><li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Settings<i class="material-icons right">arrow_drop_down</i></a></li>

      <% else %>

        <li><a href="<%= new_user_session_path  %>" class="waves-effect waves-light btn">Login</a></li>
      <% end %>
      </ul>

  </div>
</nav>