config/routes.rb
Rails.application.routes.draw do

  root 'statics#home'

  resources :photographs
  post '/profile_picture', to: 'photographs#upload_profile_pic'
  post '/change_profile_pic', to: 'photographs#change_profile_pic'

  resources :galleries
  get '/mygallery', to: 'galleries#mygallery'
  devise_for :users


  resources :users, only: [:index]
  resources :profiles do
    member do
      get 'like'
      get 'unlike'
    end
  end

  get '/myprofile', to: 'profiles#myprofile'
  get '/i_like', to: 'profiles#i_like'
  get '/likes_me', to: 'profiles#likes_me'
  get '/mutual_likes', to: 'profiles#mutual_likes'

  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]



  mount ActionCable.server => '/cable'

end

app/models/photograph.rb
class Photograph < ApplicationRecord

  require "google/cloud/vision"

  belongs_to :gallery

  mount_uploader :image, PhotographUploader

  validate :test_val

  scope :find_profile_picture, -> (gallery_id) do
    where(gallery_id: gallery_id).where(profile_picture: true)
  end



  def test_val

    project_id = "datesite"
    image_path = self.temp_url

    vision = Google::Cloud::Vision.new project: project_id
    image  = vision.image image_path

    if image.face.nil? then
      puts "has no Face"
      errors.add(:image, "Please make sure that your Profile Picture has a face on it")
      false
    else
      puts "has a Face"
      true
    end

  end


end

app/controllers/photographs_controller.rb
class PhotographsController < ApplicationController
  before_action :set_photograph, only: [:show, :edit, :update, :destroy]

  # GET /photographs
  # GET /photographs.json
  def index
    @photographs = Photograph.all
  end

  # GET /photographs/1
  # GET /photographs/1.json
  def show
  end

  # GET /photographs/new
  def new
    @photograph = Photograph.new
  end

  # GET /photographs/1/edit
  def edit
  end

  # POST /photographs
  # POST /photographs.json
  def create
    @photograph = Photograph.new(photograph_params)

    @photograph.temp_url = params["photograph"]["image"].tempfile.path
    @photograph.gallery_id = current_user.gallery.id
    @photograph.profile_picture = false

    respond_to do |format|
      if @photograph.save
        format.html { redirect_to mygallery_path, notice: 'Photograph was successfully created.' }
        format.json { render :show, status: :created, location: @photograph }
      else
        format.html { render :new }
        format.json { render json: @photograph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photographs/1
  # PATCH/PUT /photographs/1.json
  def update
    respond_to do |format|
      if @photograph.update(photograph_params)
        format.html { redirect_to @photograph, notice: 'Photograph was successfully updated.' }
        format.json { render :show, status: :ok, location: @photograph }
      else
        format.html { render :edit }
        format.json { render json: @photograph.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_profile_pic

    puts "Got POST"

    @profile = Profile.where(user_id: current_user.id).first

    @current_profile_picture = Photograph.where(profile_picture: true).first
    @current_profile_picture.update_attribute('profile_picture', false)

    @new_profile_picture = Photograph.find(params[:photoId])
    @new_profile_picture.update_attribute('profile_picture', true)
  end

  def upload_profile_pic

    @profile = Profile.where(user_id: current_user.id).first

    puts "START UPLOaD"

    @photograph = Photograph.new(photograph_params)

    @photograph.temp_url = params["photograph"]["image"].tempfile.path
    @photograph.gallery_id = current_user.gallery.id
    @photograph.profile_picture = true

    #change the current profile_picture
    @current_profile_picture = Photograph.where(profile_picture: true).first
    unless @current_profile_picture.nil?
      puts @current_profile_picture.profile_picture
      @current_profile_picture.update_attribute('profile_picture', false)
    end

    if @photograph.save
      redirect_back(fallback_location: edit_profile_path(current_user.profile.id))

    else
      redirect_back(fallback_location: edit_profile_path(current_user.profile.id))
    end

  end

  # DELETE /photographs/1
  # DELETE /photographs/1.json
  def destroy
    @photograph.destroy
    redirect_back(fallback_location: mygallery_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photograph
      @photograph = Photograph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photograph_params
      params.require(:photograph).permit(:gallery_id, :image, :profile_picture)
    end
end

app/helpers/photographs_helper.rb
module PhotographsHelper
end

app/views/photographs/_form.html.erb
<%= form_with(model: photograph, local: true) do |f| %>
  <% if photograph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photograph.errors.count, "error") %> prohibited this photograph from being saved:</h2>

      <ul>
      <% photograph.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div id="photographs_upload" class="col s12">
        <div class="col s3">
          <%= f.file_field :image, id:"gallery-file-input", hidden:true , :required => 'required'  %>
          <label for="gallery-file-input">
            <a class="waves-effect waves-light btn" style="margin-right: 10px;" ><i class="small material-icons left">add_a_photo</i> Choose New File</a>
          </label>
        </div>
        <div class="col s6">
            <div id="file-name"></div>
            <div id="preloader" class="preloader-wrapper small active" style="display:none">
              <div class="spinner-layer spinner-blue-only">
                <div class="circle-clipper left">
                  <div class="circle"></div>
                </div>
                <div class="gap-patch">
                  <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                  <div class="cirlce"></div>
                </div>
              </div>
            </div>
        </div>
        <div class="col s3">
          <%= f.submit  id:"uploadButton", class:"btn waves-effect waves-light", style:"display:none;", value:"Upload" do %>

            Upload

          <% end %>
        </div>

    </div>
  </div>
<% end %>

app/views/photographs/edit.html.erb
<h1>Editing Photograph</h1>

<%= render 'form', photograph: @photograph %>

<%= link_to 'Show', @photograph %> |
<%= link_to 'Back', photographs_path %>

app/views/photographs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photographs</h1>

<table>
  <thead>
    <tr>
      <th>Gallery</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photographs.each do |photograph| %>
      <tr>
        <td><%= photograph.gallery %></td>
        <td><%= link_to 'Show', photograph %></td>
        <td><%= link_to 'Edit', edit_photograph_path(photograph) %></td>
        <td><%= link_to 'Destroy', photograph, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photograph', new_photograph_path %>

app/views/photographs/new.html.erb
<h1>New Photograph</h1>

<%= render 'form', photograph: @photograph %>

<%= link_to 'Back', photographs_path %>

app/views/photographs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gallery:</strong>
  <%= @photograph.gallery %>
</p>

<%= link_to 'Edit', edit_photograph_path(@photograph) %> |
<%= link_to 'Back', photographs_path %>