config/routes.rb
Rails.application.routes.draw do

  root 'statics#home'

  resources :photographs
  post '/profile_picture', to: 'photographs#upload_profile_pic'
  post '/change_profile_pic', to: 'photographs#change_profile_pic'

  resources :galleries
  get '/mygallery', to: 'galleries#mygallery'
  devise_for :users


  resources :users, only: [:index]
  resources :profiles do
    member do
      get 'like'
      get 'unlike'
    end
  end

  get '/myprofile', to: 'profiles#myprofile'
  get '/i_like', to: 'profiles#i_like'
  get '/likes_me', to: 'profiles#likes_me'
  get '/mutual_likes', to: 'profiles#mutual_likes'

  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]



  mount ActionCable.server => '/cable'

end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :user

  has_many :photographs, inverse_of: :gallery

  accepts_nested_attributes_for :photographs, allow_destroy: true

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  def mygallery
    @gallery = Gallery.where(user_id: current_user.id).first
    @photograph = Photograph.new
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

      respond_to do |format|

    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:user_id)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_with(model: gallery, local: true) do |form| %>
  <% if gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :gallery_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Galleries</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.user %></td>
        <td><%= link_to 'Show', gallery %></td>
        <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
        <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/mygallery.html.erb
<div class="row">
  <div class="col s12">
    <div class="col s2"></div>
    <div class="col s8">
        <%= render 'photographs/form', photograph: @photograph, gallery: @gallery %>
    </div>
    <div class="col s2"></div>
</div>
<div class="col s12">
    <div class="col s2"></div>
    <div class="col s8">


      <div class="masonry-gallery">
        <% @gallery.photographs.each do |photo| %>
          <div class="masonry-gallery-item">

              <%= image_tag photo.image_url.to_s , class:"fit-image" %>

              <%= link_to photograph_path(photo), class:"btn-floating masonry-item-icon red", method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="material-icons" style="color:#FFF">delete</i>
              <% end %>
          </div>

        <% end %>
      </div>


    </div>
    <div class="col s2">

    </div>
  </div>
</div>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @gallery.user %>
</p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>